name        "code"
description "Manage code deployment and dependencies."
maintainer  "Vinelab"
license     "MIT"
version     "1.0.0"

depends "deploy"
depends "composer"
depends "opsworks_ecs"

recipe "code::setup", "Setup the server environment"
recipe "code::deploy", "Deploy a version of the code"
recipe "code::mount", "A workaround for Docker to mount a symlink directory"
recipe "code::env", "Prepare the environment variables read from OpsWorks (or any passed in variables) and put them in .env"
recipe "code::install_dependencies", "Run composer install inside the project directory"
recipe "code::permisisons", "Fix permissions for storage and other directories"
