name        "code"
description "Manage code deployment and dependencies."
maintainer  "Vinelab"
license     "MIT"
version     "1.0.0"

depends "deploy"
depends "composer"
depends "opsworks_ecs"

recipe "code::setup", "Setup the server environment"
recipe "code::build", "Build the project, for backend it installs dependencies (composer), for frotnend it builds it"
recipe "code::deploy", "Deploy a version of the code"
recipe "code::mount", "A workaround for Docker to mount a symlink directory"
recipe "code::env", "Prepare the environment variables read from OpsWorks (or any passed in variables) and put them in .env"
recipe "code::permisisons", "Fix permissions for storage and other directories"
